name: neyron_ai
description: "Neyron AI — Miya Sayyorasiga Sayohat"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # State management
  provider: ^6.1.5

  # UI
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.2
  lottie: ^3.3.3

  # Network & AI
  http: ^1.5.0

  # Storage
  shared_preferences: ^2.5.3

  # Utils
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
